# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mysql_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
                ('motto', models.TextField()),
                ('profession', models.CharField(max_length=11)),
                ('profession_info', models.TextField()),
                ('student', models.TextField()),
                ('student_info', models.TextField()),
                ('address', models.CharField(max_length=11)),
                ('address_info', models.TextField()),
                ('school', models.CharField(max_length=11)),
                ('school_info', models.TextField()),
            ],
            options={
                'db_table': 'info',
            },
        ),
    ]
